### ISSUE TITLE
filter columns All Testimonials page 

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#100]
Remove: Image, Tags
Add: Approved (Y/N) ; Live (Y/N) -- make these the 2 columns on the right

**Comment by ellentohn** [comment]
see earlier comment on #31.  

Sam this works but if we can add to the Live -- a "yes" option and also a "yes" option to approved that would make this work even better

**Comment by ellentohn** [comment]
I am ok with current fix as @Opoku-Agyemang clarified  that we only see a item in the filter if its in the data set -- so the filters will not an option for somethinig that is not in the data - hence in SAdmin I can see in testimonials Approved (All/Yes/No) as one of each items exist in the data while, while in Cadmin I only see Approved (All/No) because the data set does not have an YES responses. So I think we are good to go.
12:37
I will move the items from To and close them and move them to PROD thank you @Sam
