### ISSUE TITLE
can't edit/open testimonials: Infinite spinner

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#1032]
as a cadmin I'm clicking on the pencil to read and approve user submitted testimonials. Infinite spinner.

<img width="1453" alt="Screenshot 2023-06-28 at 10 15 27 PM" src="https://github.com/massenergize/frontend-admin/assets/30277868/4ed9c177-f52e-443c-8d25-95c9259804e8">

**Comment by frimpongopoku** [comment]
So @kaatvds  @BradHN1 

I tested this way: 

### Locally with code from development branch (frontend-admin & api) 

**As Community Admin & Super Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 

### Locally with code from master branch (frontend-admin & api) 
**As Community Admin & Super Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 

Same results, all worked well.


### Tested on PROD 
**As Community Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 


Everything worked well in prod as well, 🤔 . I only haven't tested as a Super Admin on PROD (as you are in the screenshot) and that is because I dont have a super admin account on PROD yet. 

But every other case seems to be working well, could it be that the deployment was taking effect at the time 🤔 ?? 
can anyone else test this again @abdullai-t @BradHN1  

Side Note:
Also, @BradHN1  when you have time, could you please upgrade `f.agyemang@alustudent.com` to have superadmin rights, so I can be testing as a super admin as well on PROD.

**Comment by frimpongopoku** [comment]
So @kaatvds  @BradHN1 

I tested this way: 

### Locally with code from development branch (frontend-admin & api) 

**As Community Admin & Super Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 

### Locally with code from master branch (frontend-admin & api) 
**As Community Admin & Super Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 

Same results, all worked well.


### Tested on PROD 
**As Community Admin**
- [X] Signed in, clicked on the pencil and everything loaded in on the edit page. 
- [X] Loaded directly into the edit page and it worked as well 


Everything worked well in prod as well, 🤔 . I only haven't tested as a Super Admin on PROD (as you are in the screenshot) and that is because I dont have a super admin account on PROD yet. 

But every other case seems to be working well, could it be that the deployment was taking effect at the time 🤔 ?? 
can anyone else test this again @abdullai-t @BradHN1  

Side Note:
Also, @BradHN1  when you have time, could you please upgrade `f.agyemang@alustudent.com` to have superadmin rights, so I can be testing as a super admin as well on PROD.

**Comment by kaatvds** [comment]
Now it works for me too. Can't reproduce.
