### ISSUE TITLE
Can't delete events

### ISSUE THREAD

**Issue by apowelka** [massenergize/frontend-admin#1121]
I accidentally created 3 copies of an event. I went to delete them, but I get an error message saying that I cannot delete templates. I did not designate these as templates. I am signed in as a community admin. Its the first 3 events, 1283-1285, in the photo.

**Comment by abdullai-t** [comment]
The reason you are unable to delete those copies might be because you copied from a template event, making those copies templates themselves. Currently, we do not permit the deletion of templates. You can delete them by navigating to the event edit page, toggling the "Is this Event a Template?" option to No, and then attempting to delete them again.

**Comment by BradHN1** [comment]
Duplicate #1076
