### ISSUE TITLE
Custom Navigation Bug Fixes

### ISSUE THREAD

**Issue by frimpongopoku** [massenergize/frontend-admin#1217]
- [x] Validate menu name 
- [x] Add live/not live feature 
- [x] Make menu item live automatically 
- [x] Preview external links
- [x] Logo after reloading does not select properly
- [X] Validation issues with parents

**Comment by BradHN1** [comment]
Customizing navigation is looking pretty good.
There are too many tickets on this, so I am leaving my comments here from Dev testing:

1. Please put the menu editing option behind a feature flag.  We may decide to allow all communities or just some to do this.
2. Change "Configure Navigation System" to "Customize User Portal Navigation (Advanced)"
3. Change "Brand Customization" to "Community Logo"
4. When editing a menu item the dialog should say "Edit Menu Item" instead of "Create New Menu Item"
5. At first when I created a new external menu item, it showed on the page as "Not Live" but in the dialog it was"Live"
