### ISSUE TITLE
adding cadmin email: too sensitive to capitals

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#177]
When Super admin or Cadmin enters the email of a user they want to add as a cadmin, any difference in email , like a capital, with the email of the user, makes the interface say that that is NOT a user.
See screenshots:
![image](https://user-images.githubusercontent.com/30277868/82228784-97d6c400-98f7-11ea-91f5-22c254404906.png)

**Comment by jkatofsky** [comment]
@kaatvds I have been unable to replicate the issue as you described - when I use the search feature to filter users on both the prod and dev sites it properly ignores capitalization.

Can you test out the search now? Maybe it's been fixed and this issue was accidentally left open?

Also I think there's a screenshot missing from this ticket - the one screenshot you attached doesn't have the interface saying "not a user". Perhaps I'm misunderstanding the issue?

**Comment by kaatvds** [comment]
HI Josh
