### ISSUE TITLE
vendors: enable selection of communities to existing vendors

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#36]
For vendors we can duplicate but after that can't assign it to a new community like we do in actions.. Would be super helpful to have the same functionality to as we have for actions for vendors and testimonials - maybe solution is: make them a template

**Comment by apowelka** [comment]
Actually, can't even see the vendors used by other communities when logged in as a community admin

**Comment by kaatvds** [comment]
I think only Sadmins can see all vendors and duplicate them (only not assign them to another community = the bug. This is not a bad thing and we should discuss: other communities, when they start promoting vendors, should let MassEn or the Community that onboarded them, and, of course, the vendor know. If we let Cadmins easily duplicate them themselves this may be too easy and this step may  be skipped. Best is, if they see a vendor they like with another community, that they reach out to onboarding comm or ME (esp if the vendor works under the ME partnership agreement).

**Comment by apowelka** [comment]
Hi Kaat -

Ok this makes sense. Framingham would like to list Black a earth compost
since they are already working in our community. We should set this process
up - maybe I should make a google form?

I do think we should be able to copy events though and that functionality
is not enabled for cadmins. I added it to a bug in github about copying
events not working.

**Comment by kaatvds** [comment]
Can't assign copied  (by Sadmin) vendor to a specific community
