### ISSUE TITLE
Housholds not counted in  donut

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#362]
On EcoNatick it says 34 actions completed (Eco Natick which is new does not have users yet, but some users in other comm have Natick HHs). None of those show in the bars. Is that because those users are not yet pat of the community? and if so, should that be corrected? It's weird for it to show on the donut but not in the bar graph
![Screenshot (1053)](https://user-images.githubusercontent.com/30277868/125091780-b7eab900-e09e-11eb-816f-9e31b987ebf6.png)

**Comment by kaatvds** [comment]
Also, I couldn't find out who those 9 HH are through any of the csvs...

**Comment by BradHN1** [comment]
I verified those HH are JCAN or other community members who live in Natick.  Because the community isn't live, they don't know about it.  I've updated the Community Users download to list non-community members who have households in the community.  They can then be invited to join.l

The bar graph is only community members, so the actions done on households of non-members don't show up.
Will get to that next
