### ISSUE TITLE
Testimonials ranking in list doesn't work

### ISSUE THREAD

**Issue by kaatvds** [massenergize/frontend-admin#587]
In the list of testimonials, the in-list ranking doesn't work.

**Comment by abdullai-t** [comment]
@kaatvds - could you add more Information

**Comment by BradHN1** [comment]
The problem had been that if you edit the ranks on the list page that it wasn't saving them, but that does appear to be working now.  However, there is a confusing Redux-related problem:  if I change a testimonial rank on the list page, then edit that testimonial, I see the old rank which is confusing.  (I assume this may be the same for actions also).  This could be fixed by reading the testimonial each time when opening the editor, or updating the redux store with the updated rank.
