### ISSUE TITLE
in edit testimonial: who wrote it?

### ISSUE THREAD

**Issue by BradHN1** [massenergize/frontend-admin#66]
ISSUE 1156
Reported on Mon Dec 09 2019 15:32:19 GMT-0500 (EST)
Reported by Kaat Vander Straeten(KAATvds@gmail.com)
PRIORITY = High
STATUS = InProgress - Submitted 

Site Url: http://admin-dev.massenergize.org/admin/edit/112/testimonial

Description:
in edit testimonial  it is not clear to Cadmin who wrote it: neither name nor email address is shown. Can we have this shown? 

User Role: Community Admin
Notes: cf issue 2111 - don't know if that is fixed yet as we can't put in testimonials

**Comment by kaatvds** [comment]
Turns out that now (now on Prod) when a user (with an account) writes a testimonial the Cadmin can see:
the name they entered: in this example Donaldtrmp
but no longer their name or email (which we have they have an account).

![image](https://user-images.githubusercontent.com/30277868/80262174-a57f8d80-865a-11ea-9338-1c387260e6cc.png)

**Comment by kaatvds** [comment]
Can we have, on the Testim page in cadmin interface:
Name of user (connected to account)
email (connected to account)
Nickname they put in when leaving testimonial

**Comment by BradHN1** [comment]
This is purely a back-end change, and I've tested a fix locally.

**Comment by kaatvds** [comment]
I left a testimonial with a preferred name. That name showed up but in the Cadmin interface testimonial edit page I see the preferred name, but my real (signed-in) name is not visible.  Cf. Screenshot:
![image](https://user-images.githubusercontent.com/30277868/83955290-544ce700-a81f-11ea-9fe6-3b6a565d22cf.png)
