### ISSUE TITLE
[Feature] Show date/time that a user last visited the portal.

### ISSUE THREAD

**Issue by Davidjwkinghorn** [massenergize/frontend-admin#758]
**User Story.**
As a cadmin (Actor/User)
I want to be able to see when various users last visited my community site. (Goal of the actor/user)
So that I can see how regularly users are engaging with my community site. (Why/What is the result)

**Additional details/context**
This can use the DeviceProfile in the DB, which should already log user visits. Since we're interested in users with profiles, this works because DeviceProfile are linked to a UserProfile any time an unlinked DeviceProfile signs in.

This information should show up in the list all users view on the admin portal.

**Acceptance criteria.**
I can see when each user in my community last visited my community site in the list of all users on the users view.

**Comment by Davidjwkinghorn** [comment]
This was requested by Megan

**Comment by BradHN1** [comment]
@frimpongopoku - I'd like to see a couple of changes:
1.  On the users list, instead of "View Records", put the date of the last visit.   Not time.. 
2. If no visits since before we started recording it, list "Before recording"
3. if there are more than one visit recorded on more than one day, then add "..." to the date of last visit, and make it a hyperlink to the popup, otherwise no hyperlink.
4. On the list of visits, just list the dates, not times, and list only one entry per date.

**Comment by frimpongopoku** [comment]
Noted @BradHN1 🤝

**Comment by frimpongopoku** [comment]
@BradHN1 I am not sure I get the second point though. Do you mean I should then list from the visit logs if they have no records since we started using footages?

**Comment by BradHN1** [comment]
Yes, if there is no information, better to say what information we have ("No visits in last x months") rather than have people dick through only to find no information.
